version: '3.8'

services:
  app-python:
    build: ./app-python
    ports:
      - "5001:5000"
    depends_on:
      - redis
    volumes:
      - ./logs/app-python:/var/log/app
    command: >
      sh -c "python app.py > /var/log/app/output.log 2>&1"

  app-node:
    build: ./app-node
    ports:
      - "3000:3000"
    depends_on:
      - redis
    volumes:
      - ./logs/app-node:/var/log/app
    command: >
      sh -c "node index.js > /var/log/app/output.log 2>&1"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus  # ✅ Volume persistente para métricas

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"

  redis-exporter:
    image: oliver006/redis_exporter
    environment:
      - REDIS_ADDR=redis:6379
    ports:
      - "9121:9121"

volumes:
  redis-data:
  grafana-data:
  prometheus-data:  # ✅ Volume declarado
