global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'app-python'
    static_configs:
      - targets: ['app-python:5000']

  - job_name: 'app-node'
    static_configs:
      - targets: ['app-node:3000']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
