{
 "title": "Node dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "RAM utilizada no momento",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total de requisições para /time no app Node.js",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "time_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Handles ativos (como sockets abertos)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nodejs_active_handles_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU utilizada",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Recursos ativos (como conexões TCP, timers, etc.)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nodejs_active_resources_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tamanho total da heap disponível",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    { "expr": "nodejs_heap_size_total_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tamanho da heap utilizada",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    { "expr": "nodejs_heap_size_used_bytes", "legendFormat": "__auto" }
   ]
  }
 ]
}