{
 "title": "Redis exporter",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": " Misses no cache",
   "type": "timeseries",
   "description": "Ótimo para calcular cache hit ratio.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(redis_keyspace_misses_total[1m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uso de memória",
   "type": "gauge",
   "description": "Mostra quanto o Redis está utilizando de memória (em bytes).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_memory_used_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Hits no cache",
   "type": "timeseries",
   "description": "Ótimo para calcular cache hit ratio.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(redis_keyspace_hits_total[1m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Comandos processados",
   "type": "stat",
   "description": "Contador total de comandos executados desde o início.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Conexões ativas",
   "type": "gauge",
   "description": "Número atual de conexões de clientes ao Redis.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_connected_clients", "legendFormat": "__auto" }
   ]
  }
 ]
}